global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: account-service
    static_configs:
      - targets: ["host.containers.internal:8080"]
    metrics_path: /metrics

  - job_name: auth-service
    static_configs:
      - targets: ["host.containers.internal:8081"]
    metrics_path: /metrics
